.TH newhope 1 "January 2, 2012" "version VERSION" "USER COMMANDS"
.SH NAME
newhope \- a RPG-action game
.SH SYNOPSIS
.B newhope
.SH DESCRIPTION
.B "New Hope"
is a RPG-action game in the spirit of Elite, where you survive as a merchant
or bandit in a post-apocalyptic world.
.SH BUGS
Many. \`New Hope`\ is still in a early alpha stage.
.B "USE AT YOUR OWN RISK"
.SH AUTHOR
Andre Wagner <andre.nho@gmail.com>
