#!/usr/bin/env lua

package.path = '../../?/init.lua;../../?.lua;;'
require 'libs'

local world = World:new(20,20)
local callbacks = {}
local g = game.Game:new(world, callbacks)

g:start()

-- vim: ts=2:sw=2:sts=2:expandtab
